version: '3.1'
services:

    db:
      image: postgres
      environment:        
        POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"
      networks:
        - backend
      volumes:
        - pgdata:/var/lib/postgresql/data/

    web:
      build: ./api
      command: python manage.py runserver 0.0.0.0:8000
      restart: always
      ports:
        - "8000:8000"
      networks:
        - backend            
      depends_on:
        - db

volumes:
    api_data:
    pgdata:

networks:  
  backend: